// Netlify Serverless Function to Save Notable Alerts to Supabase
// Endpoint: POST /api/save-alert
// Saves alerts generated by claude-alerts to the database

export async function handler(event, context) {
    if (event.httpMethod !== 'POST') {
        return {
            statusCode: 405,
            body: JSON.stringify({ error: 'Method not allowed' })
        };
    }

    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_KEY = process.env.SUPABASE_KEY;

    if (!SUPABASE_URL || !SUPABASE_KEY) {
        return {
            statusCode: 500,
            body: JSON.stringify({ error: 'Supabase credentials not configured' })
        };
    }

    try {
        const body = JSON.parse(event.body);
        const { type, title, description } = body;

        if (!type || !title || !description) {
            return {
                statusCode: 400,
                body: JSON.stringify({ error: 'Missing required fields: type, title, description' })
            };
        }

        // Save to Supabase
        const response = await fetch(`${SUPABASE_URL}/rest/v1/notable_alerts`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'apikey': SUPABASE_KEY,
                'Authorization': `Bearer ${SUPABASE_KEY}`,
                'Prefer': 'return=representation'
            },
            body: JSON.stringify({
                type,
                title,
                description,
                sent_in_digest: false
            })
        });

        if (!response.ok) {
            const errorText = await response.text();
            console.error('Supabase error:', response.status, errorText);
            return {
                statusCode: response.status,
                body: JSON.stringify({ error: 'Failed to save alert', details: errorText })
            };
        }

        const data = await response.json();

        return {
            statusCode: 200,
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                success: true,
                alert: data[0]
            })
        };

    } catch (error) {
        console.error('Error saving alert:', error);
        return {
            statusCode: 500,
            body: JSON.stringify({ error: 'Failed to save alert', message: error.message })
        };
    }
}
